### ISSUE TITLE
使用mvn jetty:run出现异常，系统找不到指定的文件

### ISSUE THREAD

**Issue by 21jhf** [Jolking/springmvc-shiro-react-redux-restful-example#3]
016-05-19 17:27:14,859 [main] DEBUG [net.sf.ehcache.config.ConfigurationHelper] - CacheDecoratorFactory not configured for defaultCache. Skipping for 'cn.oneayst.mapper.SpMapper'.
2016-05-19 17:27:15,207 [net.sf.ehcache.CacheManager@31120021] DEBUG [net.sf.ehcache.util.UpdateChecker] - Checking for update...
2016-05-19 17:27:16,146 [net.sf.ehcache.CacheManager@31120021]  INFO [net.sf.ehcache.util.UpdateChecker] - New update(s) found: 2.6.5 [http://www.terracotta.org/confluence/display/release/Release+Notes+Ehcache+Core+2.6]. Please check http://ehcache.org for the latest version.
[INFO] Started o.e.j.m.p.JettyWebAppContext@57fae983{/,file:///E:/Study/reactJS/react-redux/src/main/webapp/,AVAILABLE}{file:///E:/Study/reactJS/react-redux/src/main/webapp/}
备份数据库
2016-05-19 17:27:19,198 [pool-1-thread-1] ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler] - Unexpected error occurred in scheduled task.
java.io.IOException: Cannot run program "sh": CreateProcess error=2, 系统找不到指定的文件。
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at cn.oneayst.util.MysqlUtil.exportDataBase(MysqlUtil.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 17 more
[INFO] Started ServerConnector@34136bd1{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
[INFO] Started @16850ms
[INFO] Started Jetty Server

**Comment by 21jhf** [comment]
![image](https://cloud.githubusercontent.com/assets/9279965/15389086/b6e6f20a-1de7-11e6-881e-0aae06838e84.png)
注释掉这行代码可以了

**Comment by Jolking** [comment]
因为运行backup.sh需要shell环境， 如果你是在windows下运行的话是行不通的。
